const_value = 1

	const SNIVY      ; 1
	const SERVINE    ; 2
	const SERPERIOR  ; 3
	const TEPIG      ; 4
	const PIGNITE    ; 5
	const EMBOAR     ; 6
	const OSHAWOTT   ; 7
	const DEWOTT     ; 8
	const SAMUROTT   ; 9
	const PATRAT     ; 10
	const WATCHOG    ; 11
	const LILLIPUP   ; 12
	const HERDIER    ; 13
	const STOUTLAND  ; 14
	const PURRLOIN   ; 15
	const LIEPARD    ; 16
	const PANSAGE    ; 17
	const SIMISAGE   ; 18
	const PANSEAR    ; 19
	const SIMISEAR   ; 20
	const PANPOUR    ; 21
	const SIMIPOUR   ; 22
	const MUNNA      ; 23
	const MUSHARNA   ; 24
	const PIDOVE     ; 25
	const TRANQUILL  ; 26
	const UNFEZANT   ; 27
	const BLITZLE    ; 28
	const ZEBSTRIKA  ; 29
	const ROGGENROLA ; 30
	const BOLDORE    ; 31
	const GIGALITH   ; 32
	const WOOBAT     ; 33
	const SWOOBAT    ; 34
	const DRILBUR    ; 35
	const EXCADRILL  ; 36
	const AUDINO     ; 37
	const TIMBURR    ; 38
	const GURDURR    ; 39
	const CONKELDURR ; 40
	const TYMPOLE    ; 41
	const PALPITOAD  ; 42
	const SEISMITOAD ; 43
	const THROH      ; 44
	const SAWK       ; 45
	const SEWADDLE   ; 46
	const SWADLOON   ; 47
	const LEAVANNY   ; 48
	const VENIPEDE   ; 49
	const WHIRLIPEDE ; 50
	const SCOLIPEDE  ; 51
	const COTTONEE   ; 52
	const WHIMSICOTT ; 53
	const PETILIL    ; 54
	const LILLIGANT  ; 55
	const BASCULIN   ; 56
	const SANDILE    ; 57
	const KROKOROK   ; 58
	const KROOKODILE ; 59
	const DARUMAKA   ; 60
	const DARMANITAN ; 61
	const MARACTUS   ; 62
	const DWEBBLE    ; 63
	const CRUSTLE    ; 64
	const SCRAGGY    ; 65
	const SCRAFTY    ; 66
	const SIGILYPH   ; 67
	const YAMASK     ; 68
	const COFAGRIGUS ; 69
	const TIRTOUGA   ; 70
	const CARRACOSTA ; 71
	const ARCHEN     ; 72
	const ARCHEOPS   ; 73
	const TRUBBISH   ; 74
	const GARBODOR   ; 75
	const ZORUA      ; 76
	const ZOROARK    ; 77
	const MINCCINO   ; 78
	const CINCCINO   ; 79
	const GOTHITA    ; 80
	const GOTHORITA  ; 81
	const GOTHITELLE ; 82
	const SOLOSIS    ; 83
	const DUOSION    ; 84
	const REUNICLUS  ; 85
	const DUCKLETT   ; 86
	const SWANNA     ; 87
	const VANILLITE  ; 88
	const VANILLISH  ; 89
	const VANILLUXE  ; 90
	const DEERLING   ; 91
	const SAWSBUCK   ; 92
	const EMOLGA     ; 93
	const KARRABLAST ; 94
	const ESCAVALIER ; 95
	const FOONGUS    ; 96
	const AMOONGUSS  ; 97
	const FRILLISH   ; 98
	const JELLICENT  ; 99
	const ALOMOMOLA  ; 100
	const JOLTIK     ; 101
	const GALVANTULA ; 102
	const FERROSEED  ; 103
	const FERROTHORN ; 104
	const KLINK      ; 105
	const KLANG      ; 106
	const KLINKLANG  ; 107
	const TYNAMO     ; 108
	const EELEKTRIK  ; 109
	const EELEKTROSS ; 110
	const ELGYEM     ; 111
	const BEHEEYEM   ; 112
	const LITWICK    ; 113
	const LAMPENT    ; 114
	const CHANDELURE ; 115
	const AXEW       ; 116
	const FRAXURE    ; 117
	const HAXORUS    ; 118
	const CUBCHOO    ; 119
	const BEARTIC    ; 120
	const CRYOGONAL  ; 121
	const SHELMET    ; 122
	const ACCELGOR   ; 123
	const STUNFISK   ; 124
	const MIENFOO    ; 125
	const MIENSHAO   ; 126
	const DRUDDIGON  ; 127
	const GOLETT     ; 128
	const GOLURK     ; 129
	const PAWNIARD   ; 130
	const BISHARP    ; 131
	const BOUFFALANT ; 132
	const RUFFLET    ; 133
	const BRAVIARY   ; 134
	const VULLABY    ; 135
	const MANDIBUZZ  ; 136
	const HEATMOR    ; 137
	const DURANT     ; 138
	const DEINO      ; 139
	const ZWEILOUS   ; 140
	const HYDREIGON  ; 141
	const LARVESTA   ; 142
	const VOLCARONA  ; 143
	const COBALION   ; 144
	const TERRAKION  ; 145
	const VIRIZION   ; 146
	const TORNADUS   ; 147
	const THUNDURUS  ; 148
	const RESHIRAM   ; 149
	const ZEKROM     ; 150
	const LANDORUS   ; 151
	const KYUREM     ; 152
	const KELDEO     ; 153
	const MELOETTA   ; 154
	const GENESECT   ; 155
	const VICTINI    ; 156
	
MON_GHOST EQU 252
FOSSIL_KABUTOPS EQU 253
FOSSIL_AERODACTYL EQU 254
