const_value = 1

	const DEX_SNIVY      ; 1
	const DEX_SERVINE    ; 2
	const DEX_SERPERIOR  ; 3
	const DEX_TEPIG      ; 4
	const DEX_PIGNITE    ; 5
	const DEX_EMBOAR     ; 6
	const DEX_OSHAWOTT   ; 7
	const DEX_DEWOTT     ; 8
	const DEX_SAMUROTT   ; 9
	const DEX_PATRAT     ; 10
	const DEX_WATCHOG    ; 11
	const DEX_LILLIPUP   ; 12
	const DEX_HERDIER    ; 13
	const DEX_STOUTLAND  ; 14
	const DEX_PURRLOIN   ; 15
	const DEX_LIEPARD    ; 16
	const DEX_PANSAGE    ; 17
	const DEX_SIMISAGE   ; 18
	const DEX_PANSEAR    ; 19
	const DEX_SIMISEAR   ; 20
	const DEX_PANPOUR    ; 21
	const DEX_SIMIPOUR   ; 22
	const DEX_MUNNA      ; 23
	const DEX_MUSHARNA   ; 24
	const DEX_PIDOVE     ; 25
	const DEX_TRANQUILL  ; 26
	const DEX_UNFEZANT   ; 27
	const DEX_BLITZLE    ; 28
	const DEX_ZEBSTRIKA  ; 29
	const DEX_ROGGENROLA ; 30
	const DEX_BOLDORE    ; 31
	const DEX_GIGALITH   ; 32
	const DEX_WOOBAT     ; 33
	const DEX_SWOOBAT    ; 34
	const DEX_DRILBUR    ; 35
	const DEX_EXCADRILL  ; 36
	const DEX_AUDINO     ; 37
	const DEX_TIMBURR    ; 38
	const DEX_GURDURR    ; 39
	const DEX_CONKELDURR ; 40
	const DEX_TYMPOLE    ; 41
	const DEX_PALPITOAD  ; 42
	const DEX_SEISMITOAD ; 43
	const DEX_THROH      ; 44
	const DEX_SAWK       ; 45
	const DEX_SEWADDLE   ; 46
	const DEX_SWADLOON   ; 47
	const DEX_LEAVANNY   ; 48
	const DEX_VENIPEDE   ; 49
	const DEX_WHIRLIPEDE ; 50
	const DEX_SCOLIPEDE  ; 51
	const DEX_COTTONEE   ; 52
	const DEX_WHIMSICOTT ; 53
	const DEX_PETILIL    ; 54
	const DEX_LILLIGANT  ; 55
	const DEX_BASCULIN   ; 56
	const DEX_SANDILE    ; 57
	const DEX_KROKOROK   ; 58
	const DEX_KROOKODILE ; 59
	const DEX_DARUMAKA   ; 60
	const DEX_DARMANITAN ; 61
	const DEX_MARACTUS   ; 62
	const DEX_DWEBBLE    ; 63
	const DEX_CRUSTLE    ; 64
	const DEX_SCRAGGY    ; 65
	const DEX_SCRAFTY    ; 66
	const DEX_SIGILYPH   ; 67
	const DEX_YAMASK     ; 68
	const DEX_COFAGRIGUS ; 69
	const DEX_TIRTOUGA   ; 70
	const DEX_CARRACOSTA ; 71
	const DEX_ARCHEN     ; 72
	const DEX_ARCHEOPS   ; 73
	const DEX_TRUBBISH   ; 74
	const DEX_GARBODOR   ; 75
	const DEX_ZORUA      ; 76
	const DEX_ZOROARK    ; 77
	const DEX_MINCCINO   ; 78
	const DEX_CINCCINO   ; 79
	const DEX_GOTHITA    ; 80
	const DEX_GOTHORITA  ; 81
	const DEX_GOTHITELLE ; 82
	const DEX_SOLOSIS    ; 83
	const DEX_DUOSION    ; 84
	const DEX_REUNICLUS  ; 85
	const DEX_DUCKLETT   ; 86
	const DEX_SWANNA     ; 87
	const DEX_VANILLITE  ; 88
	const DEX_VANILLISH  ; 89
	const DEX_VANILLUXE  ; 90
	const DEX_DEERLING   ; 91
	const DEX_SAWSBUCK   ; 92
	const DEX_EMOLGA     ; 93
	const DEX_KARRABLAST ; 94
	const DEX_ESCAVALIER ; 95
	const DEX_FOONGUS    ; 96
	const DEX_AMOONGUSS  ; 97
	const DEX_FRILLISH   ; 98
	const DEX_JELLICENT  ; 99
	const DEX_ALOMOMOLA  ; 100
	const DEX_JOLTIK     ; 101
	const DEX_GALVANTULA ; 102
	const DEX_FERROSEED  ; 103
	const DEX_FERROTHORN ; 104
	const DEX_KLINK      ; 105
	const DEX_KLANG      ; 106
	const DEX_KLINKLANG  ; 107
	const DEX_TYNAMO     ; 108
	const DEX_EELEKTRIK  ; 109
	const DEX_EELEKTROSS ; 110
	const DEX_ELGYEM     ; 111
	const DEX_BEHEEYEM   ; 112
	const DEX_LITWICK    ; 113
	const DEX_LAMPENT    ; 114
	const DEX_CHANDELURE ; 115
	const DEX_AXEW       ; 116
	const DEX_FRAXURE    ; 117
	const DEX_HAXORUS    ; 118
	const DEX_CUBCHOO    ; 119
	const DEX_BEARTIC    ; 120
	const DEX_CRYOGONAL  ; 121
	const DEX_SHELMET    ; 122
	const DEX_ACCELGOR   ; 123
	const DEX_STUNFISK   ; 124
	const DEX_MIENFOO    ; 125
	const DEX_MIENSHAO   ; 126
	const DEX_DRUDDIGON  ; 127
	const DEX_GOLETT     ; 128
	const DEX_GOLURK     ; 129
	const DEX_PAWNIARD   ; 130
	const DEX_BISHARP    ; 131
	const DEX_BOUFFALANT ; 132
	const DEX_RUFFLET    ; 133
	const DEX_BRAVIARY   ; 134
	const DEX_VULLABY    ; 135
	const DEX_MANDIBUZZ  ; 136
	const DEX_HEATMOR    ; 137
	const DEX_DURANT     ; 138
	const DEX_DEINO      ; 139
	const DEX_ZWEILOUS   ; 140
	const DEX_HYDREIGON  ; 141
	const DEX_LARVESTA   ; 142
	const DEX_VOLCARONA  ; 143
	const DEX_COBALION   ; 144
	const DEX_TERRAKION  ; 145
	const DEX_VIRIZION   ; 146
	const DEX_TORNADUS   ; 147
	const DEX_THUNDURUS  ; 148
	const DEX_RESHIRAM   ; 149
	const DEX_ZEKROM     ; 150
	const DEX_LANDORUS   ; 151
	const DEX_KYUREM     ; 152
	const DEX_KELDEO     ; 153
	const DEX_MELOETTA   ; 154
	const DEX_GENESECT   ; 155
	const DEX_VICTINI    ; 156

NUM_POKEMON    EQU 156
